apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: container-mysql
      image: mysql:5.7.19
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: "loja"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"