apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
  labels:
    app: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: container-aplicacao-loja
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80